company: "pixelpoint multimedia werbe gmbh"
company_url: null
company_logo: null
location: "Klagenfurt, Carinthia, Austria"
position: "Praktikant"
employment_type: "Full-time"
start_date: "2022-08-01"
end_date: "2022-09-30"
technologies:
  - "PHP"
  - "HTML"
responsibilities:
  - "Einmonatiges Praktikum. Dort habe ich an Webprojekten mitgearbeitet und in die Design und Cybersecurity Abteilungen hineingeschnuppert."
